version: '2'
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 9001:9001
      - 1883:1883
    volumes:
      - .:/tmp
      - ./docker/mosquitto.conf:/mosquitto/config/mosquitto.conf
